name: Madre Ayahuasca
favicon: null
layout_spectrum: 0.3129088848363608
typography_spectrum: 0.5971500249579549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.30937034636735916
  saturation: 0.036470076302066445
  rhythmicContrast: 0.4752712103072554
purpose: []
