name: Madre Ayahuasca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5971500249579549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ead2a2'
    - '#9e3d0d'
    - '#377384'
    - '#ffffff'
    - '#1d1d15'
  brandStrength: 1
  lightness: 0.30937034636735916
  saturation: 0.036470076302066445
  rhythmicContrast: 0.4752712103072554
purpose: []
